name: Neural Inspect
on:
   pull_request:
      types: [opened, synchronize]
jobs:
   run-analysis:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Run AI Analysis
           uses: johanake/neural-inspect-action@v1
           with:
              github_token: ${{ secrets.GH_TOKEN }}
              api_key: ${{ secrets.API_KEY }}
